[selene]
base = "lua51"
name = "ll"

[[fmt.print.args]]
type = "..."
required = true

[[fmt.assert.args]]
type = "..."
required = true

[[fmt.panic.args]]
type = "..."
required = true

[[fmt.warn.args]]
type = "..."
required = true

[[fmt.error.args]]
type = "..."
required = true



[fs]
property = true
writable = "new-fields"

[exec]
property = true
writable = "new-fields"

[string]
property = true
writable = "new-fields"

[table]
property = true
writable = "new-fields"
