[selene]
base = "lua51"
name = "ll"


[[fmt.print.args]]
type = "..."
required = true
[[fmt.assert.args]]
type = "..."
required = true
[[fmt.panic.args]]
type = "..."
required = true
[[fmt.warn.args]]
type = "..."
required = true
[[fmt.error.args]]
type = "..."
required = true


[[fs.write.args]]
type = "string"
required = true
[[fs.write.args]]
type = "number"
required = true
[[fs.read.args]]
type = "string"
required = true
[[fs.isdir.args]]
type = "string"
required = true
[[fs.isfile.args]]
type = "string"
required = true
[[fs.mkdir.args]]
type = "string"
required = true
[[fs.rmdir.args]]
type = "string"
required = true
[[fs.chdir.args]]
type = "string"
required = true
[[fs.attributes.args]]
type = "string"
required = true
[[fs.symlinkattributes.args]]
type = "string"
required = true
[[fs.currentdir.args]]
type = "any"
required = false
[[fs.link.args]]
type = "string"
required = true
[[fs.link.args]]
type = "string"
required = true
[[fs.link.args]]
type = "bool"
required = false
[[fs.dir.args]]
type = "string"
required = true
[[fs.touch.args]]
type = "string"
required = true

[[exec.command.args]]
type = "string"
required = true
[[exec.command.args]]
type = "table"
required = false
[[exec.command.args]]
type = "table"
required = false
[[exec.command.args]]
type = "string"
required = false
[[exec.command.args]]
type = "string"
required = false
[[exec.ctx.args]]
type = "string"
required = true
[[exec.cmd.args]]
type = "string"
required = true
[exec.run]
property = true
writable = "new-fields"


[string]
property = true
writable = "new-fields"

[table]
property = true
writable = "new-fields"
